name: Frontend CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Instalar dependencias
        run: npm install

      - name: Verificar formato con Prettier
        run: npx prettier --check .

      - name: Construir el proyecto
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Descargar artefactos generados
        run: echo "Aquí irá el comando para descargar la carpeta dist"

      - name: Desplegar a Producción
        run: echo "Aquí irán los comandos de tu proveedor de hosting"